apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: osaipo-pulse-api
  labels:
    shard: internal
    paas.redhat.com/appcode: OSPO-004
  annotations:
    # PM Hub component-release-load does live multi-project Jira; default 30s → 504
    haproxy.router.openshift.io/timeout: 120s
spec:
  host: api-osaipo-pulse.apps.int.spoke.prod.us-east-1.aws.paas.redhat.com
