apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: osaipo-aspen--osaipo-pulse

resources:
- ../osaipo-eng

configMapGenerator:
- behavior: merge
  literals:
  - API_PUBLIC_URL=https://api-osaipo-pulse.apps.int.spoke.prod.us-east-1.aws.paas.redhat.com
  - AUTH_EMAIL_DOMAIN=cluster.local
  - GOOGLE_OAUTH_CALLBACK_URL=https://osaipo-pulse.apps.int.spoke.prod.us-east-1.aws.paas.redhat.com/api/modules/customer-insights/auth/google/callback
  name: osaipo-pulse-config

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/osaipo-data/osaipo-pulse-backend
  newTag: c7a04793fc049240c0736837a565632b686d570d
- name: quay.io/osaipo-data/osaipo-pulse-frontend
  newTag: a5bcb6b5a63f9afeef4b4397cf37644834bb1f66
