apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: team-tracker-data
  labels:
    paas.redhat.com/appcode: OSPO-004
  annotations:
    kubernetes.io/reclaimPolicy: Delete
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
